### ISSUE TITLE
[question] Variable attributes in the tag

### ISSUE THREAD

**Issue by jarodium** [maveius/liphte#5]
Hello

I have the following code:

```php
function makeLi($ITEM) {

echo $t->li (a::class($this->startClass),a::ariaHaspopup("true"),[
    $t->a(a::href($this->item["href"]),a::class("menu-link"),
         [
             $t->i(a::class($this->icone." menu-icon"),"&nbsp;"),
             $t->span(a::class("menu-text"),$this->item["titulo"])
         ]
    )
]);
}
```
This code receives an array like this:

```php
[ 
      "icon"=>"flaticon2-open-box", 
      "title"=>_("Dashoard"), 
      "href"=>"ecras.php",       
      "data"=>[ 
        "key"=>"value",
        "key2" => "value2"
      ],
]
```
My question is the following:

How could I add **data-key="value"** and **data-key2="value2"** with the **a:: helper**? 

If I supply an array after the a:: calls, won't the class assume i'm setting up content? I've figured that using camelCase with an a:: call ( like this a::ariaHaspopup('true') yields aria-haspopup="true". 

My initial thought was to use call_user_function, but I have some security concerns.

Best regards

**Comment by maveius** [comment]
First of all:
- Your function has one attribute $ITEM which is not used insde the function!
- $ITEM - is not recommended name for variable, the all capital letters upper case used rather for constants


When I replaced `$this->startClass` and to any string and `$this->item['href']` to `ecras.php` and `$this->item["titulo"]` to `_("Dashoard")` in single quotes, after that my code prints:

```
<li class="startclass" aria-haspopup="true"><a href="ecras.php" class="menu-link" data-key="value"><i class=" menu-icon">&nbsp;</i><span class="menu-text">_("Dashoard")</span></a></li>
```
I'm afraid that something in your code like `$this->item['href']` or `$this->startClass` or `$this->item["titulo"]` contains characters which closed my code string and after that You receive something else.

### Answer the question:

If You had known better PHP you can figured out that if You have to add custom attributes used by Angular, React or other JS like `data-key` I recommand that you can use syntax like below:
```
$dataKey = 'data-key'
a::$dataKey('value')
```

**Comment by jarodium** [comment]
Hi
I have to apology for the poor code example, but since I made the post time constrained, it lacked some obvious stuff.

I will try to use the [data] elements with your suggestion and will let you know if it workds.
For the time being I will close this comment.

Thank you for your help

Best regards
